[build-system]
requires = [
    "setuptools>=61.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "rna-pk-fold"
version = "1.1.0"
description = "Optimal RNA Secondary Structure Prediction with Pseudoknots using the Rivas & Eddy Dynamic Programming Algorithm"
readme = "README.md"
license = { text = "MIT License" }
authors = [
    { name = "Christopher van den Berg", email = "cvandenberg1105@googlemail.com" }
]
keywords = ["rna", "pseudoknots", "dynamic-programming", "bioinformatics", "folding"]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
requires-python = ">=3.10"

# Core Runtime Dependencies
dependencies = [
    "numpy>=1.26.0, <2.3.0",
    "numba>=0.62.1, <1.0",
    "PyYAML>=6.0.3, <7.0",
    "tqdm>=4.67.1, <5.0",
]

[project.optional-dependencies]
# Unit/Integration Testing Dependencies
test = [
    "pytest==8.4.2"
]

# Jupyter Dependencies
notebook = [
    "ipython==8.12.3",
    "jupyter_client==8.6.3",
    "jupyter_core==5.8.1",
    "nbformat==5.10.4",
    "nbclient==0.10.2",
    "nbconvert==7.16.6",
    "pyzmq==27.1.0",
    "traitlets==5.14.3",
    "Pygments==2.19.2",
    "prompt_toolkit==3.0.52",
    "jupyterlab_pygments==0.3.0",
    "mistune==3.1.4",
    "bleach==6.2.0",
    "defusedxml==0.7.1",
    "jedi==0.19.2",
    "matplotlib-inline==0.1.7",
    "wcwidth==0.2.14"
]

# Plotting Dependencies
viz = [
    "matplotlib==3.10.7",
    "contourpy==1.3.2",
    "cycler==0.12.1",
    "fonttools==4.60.1",
    "kiwisolver==1.4.9",
    "pillow==11.3.0",
    "pyparsing==3.2.5",
    "python-dateutil==2.9.0.post0",
    "packaging==25.0"
]

# Core Zucker Comparison Tools
compare = [
    "seqfold==0.9.0"
]

# Developer Dependencies
dev = [
    # Testing
    "pytest==8.4.2",

    # Notebook
    "ipython==8.12.3",
    "jupyter_client==8.6.3",
    "jupyter_core==5.8.1",
    "nbformat==5.10.4",
    "nbclient==0.10.2",
    "nbconvert==7.16.6",
    "pyzmq==27.1.0",
    "traitlets==5.14.3",
    "Pygments==2.19.2",
    "prompt_toolkit==3.0.52",
    "jupyterlab_pygments==0.3.0",
    "mistune==3.1.4",
    "bleach==6.2.0",
    "defusedxml==0.7.1",
    "jedi==0.19.2",
    "matplotlib-inline==0.1.7",
    "wcwidth==0.2.14",

    # Plotting/Visualization
    "matplotlib==3.10.7",
    "contourpy==1.3.2",
    "cycler==0.12.1",
    "fonttools==4.60.1",
    "kiwisolver==1.4.9",
    "pillow==11.3.0",
    "pyparsing==3.2.5",
    "python-dateutil==2.9.0.post0",
    "packaging==25.0",

    # General Tooling & Utilities
    "requests==2.32.5",
    "urllib3==2.5.0",
    "idna==3.10",
    "certifi==2025.10.5",
    "charset-normalizer==3.4.3",
    "lxml==4.9.2",
    "beautifulsoup4==4.14.2",
    "soupsieve==2.8",
    "asttokens==3.0.0",
    "executing==2.2.1",
    "stack-data==0.6.3",
    "decorator==5.2.1",
    "attrs==25.4.0",
    "platformdirs==4.5.0",
    "typing_extensions==4.15.0",
    "tomli==2.2.1",
    "tornado==6.5.2",
    "tinycss2==1.4.0",
    "webencodings==0.5.1",

    # JSON/Schema Utils
    "jsonschema==4.25.1",
    "jsonschema-specifications==2025.9.1",
    "referencing==0.36.2",
    "rpds-py==0.27.1",

    # Optional Helpers for Regenerating Requirements Files
    "pipreqs==0.5.0",
    "yarg==0.1.9"
]


[project.urls]
Repository = "https://github.com/c-vandenberg/rna-pk-fold"
"Bug Tracker" = "https://github.com/c-vandenberg/rna-pk-fold/issues"

[project.scripts]
rna-pk-fold = "rna_pk_fold.scripts.predict_rna:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["rna_pk_fold*"]

[tool.setuptools.package-data]
"rna_pk_fold.data" = ["*.yaml"]
