from __future__ import annotations
from typing import List, Tuple, Dict, Set, Callable, Any
import time
import logging

from rna_pk_fold.structures import Pair
from rna_pk_fold.folding.common_traceback import pairs_to_multilayer_dotbracket, TraceResult
from rna_pk_fold.folding.eddy_rivas.eddy_rivas_fold_state import EddyRivasFoldState
from rna_pk_fold.folding.eddy_rivas.eddy_rivas_dynamic_programming import EddyRivasBacktrackOp
from rna_pk_fold.utils.dynamic_programming.traceback_ops_utils import (merge_nested_region_pairs,
                                                                       place_pair_in_first_non_crossing_layer,
                                                                       audit_layer_assignments,
                                                                       choose_pk_branch)
from rna_pk_fold.utils.dynamic_programming.back_pointer_utils import (get_wx_backpointer, get_whx_backpointer,
                                                                      get_yhx_backpointer, get_zhx_backpointer,
                                                                      get_vhx_backpointer)
from rna_pk_fold.utils.dynamic_programming.dp_split_utils import validate_left_split_index, validate_right_split_index

logger = logging.getLogger(__name__)

PROGRESS_OPS_WHX = {
    EddyRivasBacktrackOp.RE_WHX_SHRINK_LEFT,
    EddyRivasBacktrackOp.RE_WHX_SHRINK_RIGHT,
    EddyRivasBacktrackOp.RE_WHX_TRIM_LEFT,
    EddyRivasBacktrackOp.RE_WHX_TRIM_RIGHT,
    EddyRivasBacktrackOp.RE_WHX_SS_BOTH,
    EddyRivasBacktrackOp.RE_WHX_SPLIT_LEFT_WHX_WX,
    EddyRivasBacktrackOp.RE_WHX_SPLIT_RIGHT_WX_WHX,
    EddyRivasBacktrackOp.RE_WHX_OVERLAP_SPLIT,
    EddyRivasBacktrackOp.RE_WHX_COLLAPSE,
}

PROGRESS_OPS_YHX = {
    EddyRivasBacktrackOp.RE_YHX_DANGLE_L,
    EddyRivasBacktrackOp.RE_YHX_DANGLE_R,
    EddyRivasBacktrackOp.RE_YHX_DANGLE_LR,
    EddyRivasBacktrackOp.RE_YHX_SS_LEFT,
    EddyRivasBacktrackOp.RE_YHX_SS_RIGHT,
    EddyRivasBacktrackOp.RE_YHX_SS_BOTH,
    EddyRivasBacktrackOp.RE_YHX_SPLIT_LEFT_YHX_WX,
    EddyRivasBacktrackOp.RE_YHX_SPLIT_RIGHT_WX_YHX,
    EddyRivasBacktrackOp.RE_YHX_WRAP_WHX,
    EddyRivasBacktrackOp.RE_YHX_WRAP_WHX_L,
    EddyRivasBacktrackOp.RE_YHX_WRAP_WHX_R,
    EddyRivasBacktrackOp.RE_YHX_WRAP_WHX_LR,
}

PROGRESS_OPS_ZHX = {
    EddyRivasBacktrackOp.RE_ZHX_FROM_VHX,
    EddyRivasBacktrackOp.RE_ZHX_DANGLE_L,
    EddyRivasBacktrackOp.RE_ZHX_DANGLE_R,
    EddyRivasBacktrackOp.RE_ZHX_DANGLE_LR,
    EddyRivasBacktrackOp.RE_ZHX_SS_LEFT,
    EddyRivasBacktrackOp.RE_ZHX_SS_RIGHT,
    EddyRivasBacktrackOp.RE_ZHX_SPLIT_LEFT_ZHX_WX,
    EddyRivasBacktrackOp.RE_ZHX_SPLIT_RIGHT_ZHX_WX,
}

PROGRESS_OPS_VHX = {
    EddyRivasBacktrackOp.RE_VHX_DANGLE_L,
    EddyRivasBacktrackOp.RE_VHX_DANGLE_R,
    EddyRivasBacktrackOp.RE_VHX_DANGLE_LR,
    EddyRivasBacktrackOp.RE_VHX_SS_LEFT,
    EddyRivasBacktrackOp.RE_VHX_SS_RIGHT,
    EddyRivasBacktrackOp.RE_VHX_SPLIT_LEFT_ZHX_WX,
    EddyRivasBacktrackOp.RE_VHX_SPLIT_RIGHT_ZHX_WX,
    EddyRivasBacktrackOp.RE_VHX_WRAP_WHX,
    EddyRivasBacktrackOp.RE_VHX_CLOSE_BOTH,
}

def _target_will_progress_to_whx(state, i, j, k, l) -> bool:
    bp = get_whx_backpointer(state, i, j, k, l)
    return (bp is not None) and (bp.op in PROGRESS_OPS_WHX)

def _target_will_progress_to_yhx(state, i, j, k, l) -> bool:
    bp = get_yhx_backpointer(state, i, j, k, l)
    return (bp is not None) and (bp.op in PROGRESS_OPS_YHX)

def _target_will_progress_to_zhx(state, i, j, k, l) -> bool:
    bp = get_zhx_backpointer(state, i, j, k, l)
    return (bp is not None) and (bp.op in PROGRESS_OPS_ZHX)

def _target_will_progress_to_vhx(state, i, j, k, l) -> bool:
    bp = get_vhx_backpointer(state, i, j, k, l)
    return (bp is not None) and (bp.op in PROGRESS_OPS_VHX)


def traceback_with_pseudoknots(
    seq: str,
    *,
    nested_state: Any,
    eddy_rivas_fold_state: EddyRivasFoldState,
    trace_nested_interval: Callable[[str, Any, int, int], TraceResult],
) -> TraceResult:
    """
    Reconstructs the optimal RNA secondary structure, including pseudoknots.

    This function implements a stack-based state machine to navigate the
    backpointers generated by the Rivas-Eddy dynamic programming algorithm.
    It starts from the top-level structure `WX(0, N-1)` and recursively
    decomposes it into smaller subproblems (frames) until the entire
    structure is resolved into a set of base pairs.

    Nested substructures are delegated to an external traceback function,
    allowing this implementation to focus solely on resolving the pseudoknotted
    grammar.

    Parameters
    ----------
    seq : str
        The RNA sequence that was folded.
    nested_state : Any
        The state object from the nested-only folding engine (e.g.,
        ZuckerFoldState). This is treated as an opaque object and is passed
        directly to the `trace_nested_interval` function.
    eddy_rivas_fold_state : EddyRivasFoldState
        The state object containing the filled dynamic programming matrices
        and backpointers from the Rivas-Eddy algorithm.
    trace_nested_interval : Callable[[str, Any, int, int], TraceResult]
        A function responsible for tracing a purely nested secondary
        structure within a given interval `[i, j]`.

    Returns
    -------
    TraceResult
        A data object containing the final list of base pairs and the
        corresponding multilayer dot-bracket string representation.
    """
    start_time = time.perf_counter()

    seq_len = eddy_rivas_fold_state.seq_len
    if seq_len == 0:
        return TraceResult(pairs=[], dot_bracket="")

    logger.info(f"Starting traceback for sequence length N={seq_len}")

    initial_backpointer = get_wx_backpointer(eddy_rivas_fold_state, 0, seq_len - 1)
    print(f"[TB START] WX[0,{seq_len - 1}] BP: {initial_backpointer}", flush=True)

    # --- State Initialization ---
    # A "trace frame" is a tuple: (TAG, *coordinates, layer)
    # - TAG is one of {"WX", "WHX", "YHX", "ZHX", "VHX"}
    # - Coordinates depend on TAG:
    #     WX:  (i, j, layer)
    #     WHX: (i, j, k, l, layer)
    #     YHX: (i, j, k, l, layer)
    #     ZHX: (i, j, k, l, layer)
    #     VHX: (i, j, k, l, layer)
    TraceFrame = Tuple

    # Start with the entire sequence as a WX problem on layer 0.
    trace_stack: List[TraceFrame] = [("WX", 0, seq_len - 1, 0)]

    # `base_pairs` will store the final set of (i, j) base pairs.
    base_pairs: Set[Pair] = set()

    # `pair_to_layer` maps each base pair to its assigned dot-bracket layer.
    pair_to_layer: Dict[Tuple[int, int], int] = {}

    # --- Debugging Block ---
    # This block probes the initial backpointer for the full sequence to provide
    # immediate insight into the top-level structure/WX decision (nested vs. pseudoknotted).
    top_backpointer = get_wx_backpointer(eddy_rivas_fold_state, 0, seq_len - 1)
    if top_backpointer:
        print(
            f"[WX WIN] op={top_backpointer.op} split={top_backpointer.split} "
            f"hole={top_backpointer.hole} hole_left={top_backpointer.hole_left} hole_right={top_backpointer.hole_right}",
            flush=True
        )
    else:
        print("[WX WIN] None → nested only", flush=True)

    # If the top-level structure is a composition, probe the subproblem backpointers.
    if top_backpointer and top_backpointer.op in (
        EddyRivasBacktrackOp.RE_PK_COMPOSE_WX_YHX_WHX,
        EddyRivasBacktrackOp.RE_PK_COMPOSE_WX_WHX_YHX,
        EddyRivasBacktrackOp.RE_PK_COMPOSE_WX_YHX,
        EddyRivasBacktrackOp.RE_PK_COMPOSE_WX,
    ):
        # Determine the exact coordinates of the left and right sub-holes.
        split_index = top_backpointer.split
        if top_backpointer.hole_left:
            left_k, left_l = top_backpointer.hole_left
        else:
            left_k, left_l = (top_backpointer.hole[0], split_index) if top_backpointer.hole else (None, None)

        if top_backpointer.hole_right:
            right_k, right_l = top_backpointer.hole_right
        else:
            _, l_idx = top_backpointer.hole if top_backpointer.hole else (None, None)
            right_k, right_l = (split_index + 1, l_idx)

        # Check if backpointers exist for the specific subproblems that will be traced.
        y_bp = get_yhx_backpointer(eddy_rivas_fold_state, 0, split_index, left_k, left_l)
        w_bp = get_whx_backpointer(eddy_rivas_fold_state, split_index + 1, seq_len - 1, right_k, right_l)

        print(f"[PROBE] YHX[0,{split_index}:{left_k},{left_l}] BP?",
              "yes" if y_bp else "no",
              f"op={getattr(y_bp, 'op', None)}", flush=True)
        print(f"[PROBE] WHX[{split_index + 1},{seq_len - 1}:{right_k},{right_l}] BP?",
              "yes" if w_bp else "no",
              f"op={getattr(w_bp, 'op', None)}", flush=True)

    # --- Main Traceback Loop ---
    # Process trace frames from the stack until all sub-problems are resolved.
    while trace_stack:
        # Pop the next subproblem to work on.
        trace_frame = trace_stack.pop()
        tag = trace_frame[0]

        # --- 1. WX Frame Processing ---
        # WX represents the most general problem for an interval [i, j].
        if tag == "WX":
            _, outer_start, outer_end, layer_idx = trace_frame
            backpointer = get_wx_backpointer(eddy_rivas_fold_state, outer_start, outer_end)

            if outer_start == 0 and outer_end == seq_len - 1:
                print(f"[WX PROCESS] bp={backpointer}", flush=True)
                if backpointer:
                    print(f"  op={backpointer.op}", flush=True)

            # 1.1. If no backpointer, or if the backpointer explicitly selects the 'uncharged' (nested) path...
            if not backpointer or backpointer.op is EddyRivasBacktrackOp.RE_WX_SELECT_UNCHARGED:
                if outer_start == 0 and outer_end == seq_len - 1:
                    print(f"  → Going nested!", flush=True)
                # ...delegate this entire interval to the nested traceback function.
                merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                          trace_nested_interval, base_pairs, pair_to_layer)
                continue

            if outer_start == 0 and outer_end == seq_len - 1:
                print(f"  → Processing PK composition!", flush=True)

            op = backpointer.op
            split_index = backpointer.split
            k_idx, l_idx = (backpointer.hole if backpointer.hole is not None else (None, None))

            # 1.2. Handle WX composition from two WHX subproblems.
            if op is EddyRivasBacktrackOp.RE_PK_COMPOSE_WX:
                # derive left/right coordinates
                if backpointer.hole_left and backpointer.hole_right:
                    left_k, left_l = backpointer.hole_left
                    right_k, right_l = backpointer.hole_right
                else:
                    left_k, left_l = k_idx, split_index
                    right_k, right_l = split_index + 1, l_idx

                # If the WX composition explicitly indicated a pseudoknot (has_pk),
                # reconstruct it deterministically: place the composed inner hole
                # pairs on a dedicated PK layer and merge nested left/right
                # contents on the base layer. This avoids fragile YHX→WHX
                # handoffs that often collapse the hole during traceback.
                prefer_crossing = bool(getattr(backpointer, 'has_pk', False))

                if getattr(backpointer, 'has_pk', False):
                    try:
                        existing_max_layer = max(pair_to_layer.values()) if pair_to_layer else -1
                    except Exception:
                        existing_max_layer = -1
                    # Ensure PK brackets are at least on layer 1 so they are
                    # rendered with a distinct bracket type above nested layer 0.
                    pk_layer = max(1, existing_max_layer + 1)

                    # Place the composed inner pairs (these are the short helix
                    # boundaries chosen by the WX composition kernel).
                    try:
                        place_pair_in_first_non_crossing_layer(base_pairs, pair_to_layer, left_k, left_l, pk_layer)
                    except Exception:
                        pass
                    try:
                        place_pair_in_first_non_crossing_layer(base_pairs, pair_to_layer, right_k, right_l, pk_layer)
                    except Exception:
                        pass

                    # Collect nested pairs for left and right outer spans, but do
                    # not yet merge them into `base_pairs`. We'll reconcile them
                    # against the composed PK bases to avoid double-pairing.
                    try:
                        left_trace = trace_nested_interval(seq, nested_state, outer_start, left_l)
                    except Exception:
                        left_trace = TraceResult(pairs=[], dot_bracket="")
                    try:
                        right_trace = trace_nested_interval(seq, nested_state, right_k, outer_end)
                    except Exception:
                        right_trace = TraceResult(pairs=[], dot_bracket="")

                    # Determine PK base indices we must not reuse in nested pairs.
                    pk_indices = {left_k, left_l, right_k, right_l}

                    # Filter out any nested pair that shares a nucleotide with the PK
                    # inner helices (cannot double-pair). Keep the rest.
                    kept_nested_pairs = []
                    for pair in getattr(left_trace, 'pairs', []) + getattr(right_trace, 'pairs', []):
                        if (pair.base_i in pk_indices) or (pair.base_j in pk_indices):
                            # Log a debug note about conflict removal.
                            print(f"[PK RECONCILE] Dropping nested pair ({pair.base_i},{pair.base_j}) due to PK indices {pk_indices}", flush=True)
                            continue
                        kept_nested_pairs.append(pair)

                    # Place all kept nested pairs on the base layer (0) using
                    # layer-safe placement so they don't create intra-layer crossings.
                    for pair in kept_nested_pairs:
                        place_pair_in_first_non_crossing_layer(base_pairs, pair_to_layer, pair.base_i, pair.base_j, 0)

                    # Force the composed inner pairs onto the PK layer so they
                    # remain visible even if nested merges would have conflicted.
                    try:
                        li, lj = min(left_k, left_l), max(left_k, left_l)
                        ri, rj = min(right_k, right_l), max(right_k, right_l)
                        base_pairs.add(Pair(li, lj))
                        base_pairs.add(Pair(ri, rj))
                        pair_to_layer[(li, lj)] = pk_layer
                        pair_to_layer[(ri, rj)] = pk_layer
                        print(f"[PK FORCE] ({li},{lj}) and ({ri},{rj}) -> L{pk_layer}", flush=True)
                    except Exception:
                        pass

                    # Simple validation: report the DP's WX energy for this outer span
                    # so the user can compare it to the reconstructed structure.
                    try:
                        dp_energy = eddy_rivas_fold_state.wx_matrix.get_energy(outer_start, outer_end)
                        print(f"[PK VALIDATE] WX[{outer_start},{outer_end}] DP energy = {dp_energy}", flush=True)
                    except Exception:
                        pass

                    continue

                # Fallback: if not a declared PK by the composition kernel, proceed
                # with the regular choose_pk_branch logic below.
                left_choice, (li, lj, lk, ll) = choose_pk_branch(
                    eddy_rivas_fold_state, "L", outer_start, left_l, left_k, left_l, prefer_crossing
                )
                right_choice, (ri, rj, rk, rl) = choose_pk_branch(
                    eddy_rivas_fold_state, "R", right_k, outer_end, right_k, right_l, prefer_crossing
                )

                # If choose_pk_branch selected YHX, but the YHX backpointer will
                # immediately hand off to WHX (via IS2 or WRAP), downgrade to
                # WHX to avoid a transient YHX → WHX collapse that loses PK pairs.
                def yhx_will_handoff_to_whx(state, i, j, k, l):
                    ybp = get_yhx_backpointer(state, i, j, k, l)
                    if not ybp:
                        return False
                    # Immediate YHX ops that wrap/hand off to WHX
                    if ybp.op in (
                        EddyRivasBacktrackOp.RE_YHX_IS2_INNER_WHX,
                        EddyRivasBacktrackOp.RE_YHX_WRAP_WHX,
                        EddyRivasBacktrackOp.RE_YHX_WRAP_WHX_L,
                        EddyRivasBacktrackOp.RE_YHX_WRAP_WHX_R,
                        EddyRivasBacktrackOp.RE_YHX_WRAP_WHX_LR,
                    ):
                        return True
                    # If YHX has a bridge that would progress to WHX, prefer WHX
                    if getattr(ybp, 'bridge', None):
                        bi, bj = ybp.bridge
                        return _target_will_progress_to_whx(state, bi, bj, k, l)
                    return False

                if left_choice == "YHX" and yhx_will_handoff_to_whx(eddy_rivas_fold_state, li, lj, lk, ll):
                    print(f"[WX ADJUST] Left YHX -> WHX due to imminent handoff", flush=True)
                    left_choice = "WHX"
                if right_choice == "YHX" and yhx_will_handoff_to_whx(eddy_rivas_fold_state, ri, rj, rk, rl):
                    print(f"[WX ADJUST] Right YHX -> WHX due to imminent handoff", flush=True)
                    right_choice = "WHX"

                # Push right branch first so left runs next (stack is LIFO)
                if right_choice == "YHX":
                    trace_stack.append(("YHX", ri, rj, rk, rl, layer_idx))
                else:
                    # WHX or FLATTEN: merge the nested WX interval on the provided layer
                    merge_nested_region_pairs(seq, nested_state, ri, rj, layer_idx,
                                            trace_nested_interval, base_pairs, pair_to_layer)

                # Left side
                if left_choice == "YHX":
                    trace_stack.append(("YHX", li, lj, lk, ll, layer_idx))
                else:
                    merge_nested_region_pairs(seq, nested_state, li, lj, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)
                continue

            # 1.3. Handle WX composition from two YHX subproblems.
            if op is EddyRivasBacktrackOp.RE_PK_COMPOSE_WX_YHX:
                if backpointer.hole_left and backpointer.hole_right:
                    left_k, left_l = backpointer.hole_left
                    right_k, right_l = backpointer.hole_right
                else:
                    left_k, left_l = k_idx, split_index
                    right_k, right_l = split_index + 1, l_idx

                trace_stack.append(("YHX", outer_start, left_l, left_k, left_l, layer_idx))
                trace_stack.append(("YHX", right_k, outer_end, right_k, right_l, layer_idx))
                continue

            # 1.4. Handle WX composition from two overlapping YHX subproblems.
            if op is EddyRivasBacktrackOp.RE_PK_COMPOSE_WX_YHX_OVERLAP:
                # Both branches share the same (k,l); no BPs are needed—YHX will place (k,l) on entry
                trace_stack.append(("YHX", outer_start, split_index, k_idx, l_idx, layer_idx))
                trace_stack.append(("YHX", split_index + 1, outer_end, k_idx, l_idx, layer_idx))
                continue

            # 1.5. Handle WX composition from a YHX (crossing) and a WHX (nested) subproblem.
            if op is EddyRivasBacktrackOp.RE_PK_COMPOSE_WX_YHX_WHX:
                if backpointer.hole_left and backpointer.hole_right:
                    left_k, left_l = backpointer.hole_left
                    right_k, right_l = backpointer.hole_right
                else:
                    left_k, left_l = k_idx, split_index
                    right_k, right_l = split_index + 1, l_idx

                trace_stack.append(("YHX", outer_start, left_l, left_k, left_l, layer_idx))
                trace_stack.append(("WHX", right_k, outer_end, right_k, right_l, 0))
                continue

            # 1.6. Handle WX composition from a WHX (nested) and a YHX (crossing) subproblem.
            if op is EddyRivasBacktrackOp.RE_PK_COMPOSE_WX_WHX_YHX:
                if backpointer.hole_left and backpointer.hole_right:
                    left_k, left_l = backpointer.hole_left
                    right_k, right_l = backpointer.hole_right
                else:
                    left_k, left_l = k_idx, split_index
                    right_k, right_l = split_index + 1, l_idx

                if outer_start == 0 and outer_end == seq_len - 1:
                    print(f"  [PUSH] WHX({outer_start}, {left_l}, {left_k}, {left_l}, 0)", flush=True)
                    print(f"  [PUSH] YHX({right_k}, {outer_end}, {right_k}, {right_l}, {layer_idx})", flush=True)

                trace_stack.append(("WHX", outer_start, left_l, left_k, left_l, 0))
                trace_stack.append(("YHX", right_k, outer_end, right_k, right_l, layer_idx))
                continue

            # 1.6. Fallback for any other WX operation: treat as a simple nested interval.
            merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                      trace_nested_interval, base_pairs, pair_to_layer)
            continue

        # --- 2. WHX Frame Processing ---
        # WHX is a gapped structure with undetermined pairing at all ends.
        if tag == "WHX":
            _, outer_start, outer_end, k_idx, l_idx, layer_idx = trace_frame

            if k_idx + 1 == l_idx:
                print(f"[WHX COLLAPSE] ({outer_start},{outer_end}:{k_idx},{l_idx}) → nested", flush=True)
                merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                          trace_nested_interval, base_pairs, pair_to_layer)
                continue

            logger.debug(f"\n=== WHX[{outer_start},{outer_end},{k_idx},{l_idx}] layer={layer_idx} ===")
            backpointer = get_whx_backpointer(eddy_rivas_fold_state, outer_start, outer_end, k_idx, l_idx)

            # 2.1. If no backpointer, it implies the hole collapsed. Treat the outer span as nested.
            if not backpointer:
                print(f"[WHX MISS] merging nested [{outer_start},{outer_end}] hole=({k_idx},{l_idx}) layer={layer_idx}",
                      flush=True)
                merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                          trace_nested_interval, base_pairs, pair_to_layer)
                continue

            op = backpointer.op

            # 2.2. Add an unpaired base at the 5' end of the hole. Push the smaller subproblem.
            if op is EddyRivasBacktrackOp.RE_WHX_SHRINK_LEFT:
                if (k_idx + 1) + 1 == l_idx:
                    # Shrinking left leads to collapse: WHX(i,j:k+1,l) where (k+1)+1==l
                    print(f"[WHX TRANSITIVE COLLAPSE] ({outer_start},{outer_end}:{k_idx},{l_idx}) shrink→collapse",
                          flush=True)
                    merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)
                    continue
                trace_stack.append(("WHX", outer_start, outer_end, k_idx + 1, l_idx, layer_idx))

            # 2.3. Add an unpaired base at the 3' end of the hole.
            elif op is EddyRivasBacktrackOp.RE_WHX_SHRINK_RIGHT:
                if k_idx + 1 == (l_idx - 1):
                    print(f"[WHX TRANSITIVE COLLAPSE] ({outer_start},{outer_end}:{k_idx},{l_idx}) shrink→collapse",
                          flush=True)
                    merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)
                    continue
                trace_stack.append(("WHX", outer_start, outer_end, k_idx, l_idx - 1, layer_idx))

            # 2.4. Add an unpaired base at the 5' end of the outer span.
            elif op is EddyRivasBacktrackOp.RE_WHX_TRIM_LEFT:
                trace_stack.append(("WHX", outer_start + 1, outer_end, k_idx, l_idx, layer_idx))

            # 2.5. Add an unpaired base at the 3' end of the outer span.
            elif op is EddyRivasBacktrackOp.RE_WHX_TRIM_RIGHT:
                trace_stack.append(("WHX", outer_start, outer_end - 1, k_idx, l_idx, layer_idx))

            # 2.6. Add unpaired bases at both outer ends.
            elif op is EddyRivasBacktrackOp.RE_WHX_SS_BOTH:
                trace_stack.append(("WHX", outer_start + 1, outer_end - 1, k_idx, l_idx, layer_idx))

            # 2.7. The hole has collapsed into a purely nested structure.
            elif op is EddyRivasBacktrackOp.RE_WHX_COLLAPSE:
                if backpointer.outer:
                    oi, oj = backpointer.outer
                    merge_nested_region_pairs(seq, nested_state, oi, oj, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)
                else:
                    merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)

            # 2.8. Bifurcation into a smaller WHX and a nested WX.
            elif op is EddyRivasBacktrackOp.RE_WHX_SPLIT_LEFT_WHX_WX:
                split_index = validate_left_split_index(outer_start, outer_end, backpointer.split)
                if split_index is None:
                    # Do not progress split to avoid infinite loop. Fallback to nested merge of the whole span.
                    print(
                        f"[WHX SPLIT LEFT] non-progress split (split={backpointer.split}) → merge [{outer_start},{outer_end}]",
                        flush=True)
                    merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)
                    continue

                # Left WHX strictly smaller than current
                trace_stack.append(("WHX", outer_start, split_index, k_idx, l_idx, layer_idx))

                # Right WX segment only if non-empty
                if split_index + 1 <= outer_end:
                    merge_nested_region_pairs(seq, nested_state, split_index + 1, outer_end, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)

            # 2.9. Bifurcation into a nested WX and a smaller WHX.
            elif op is EddyRivasBacktrackOp.RE_WHX_SPLIT_RIGHT_WX_WHX:
                split_index = validate_right_split_index(outer_start, outer_end, backpointer.split)
                if split_index is None:
                    # Non-progress split → avoid infinite loop. Fallback to nested merge of the whole span.
                    print(
                        f"[WHX SPLIT RIGHT] non-progress split (split={backpointer.split}) → merge [{outer_start},{outer_end}]",
                        flush=True)
                    merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)
                    continue

                    # Left WX segment only if non-empty
                if outer_start <= split_index:
                    merge_nested_region_pairs(seq, nested_state, outer_start, split_index, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)

                    # Right WHX only if it strictly advances
                if split_index + 1 <= outer_end:
                    trace_stack.append(("WHX", split_index + 1, outer_end, k_idx, l_idx, layer_idx))

            # 2.10. Overlapping pseudoknot from two smaller WHX subproblems.
            elif op is EddyRivasBacktrackOp.RE_WHX_OVERLAP_SPLIT:
                split_index = validate_left_split_index(outer_start, outer_end, backpointer.split)
                if split_index is None:
                    print(
                        f"[WHX OVERLAP] non-progress split (split={backpointer.split}) → merge [{outer_start},{outer_end}]",
                        flush=True)
                    merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)
                    continue

                trace_stack.append(("WHX", outer_start, split_index, k_idx, l_idx, layer_idx))
                trace_stack.append(("WHX", split_index + 1, outer_end, k_idx, l_idx, layer_idx))

            # 2.11 IS2 route that resolves the inner hole via YHX logic.
            elif op is EddyRivasBacktrackOp.RE_WHX_IS2_INNER_YHX:
                if backpointer.bridge:
                    yi, yj = backpointer.bridge
                    strict_subspan = (outer_start <= yi <= yj <= outer_end) and ((yi, yj) != (outer_start, outer_end))
                    equal_span = (yi, yj) == (outer_start, outer_end)
                    ok_not_hole = ((yi, yj) != (k_idx, l_idx))
                    if (strict_subspan or (
                            equal_span and _target_will_progress_to_yhx(eddy_rivas_fold_state, yi, yj, k_idx,
                                                                        l_idx))) and ok_not_hole:
                        print(f"[WHX IS2] handoff → YHX({yi},{yj}:{k_idx},{l_idx})", flush=True)
                        trace_stack.append(("YHX", yi, yj, k_idx, l_idx, layer_idx))
                        continue
                    print("[WHX IS2] bridge rejected (non-progress or equals hole) → merge nested", flush=True)
                    merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)
                else:
                    print("[WHX IS2] missing bridge → merge nested", flush=True)
                    merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)
                continue

            else:
                # Fallback for unknown operations.
                logger.warning(f"Unknown WHX op: {op}, falling back to nested")
                merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                          trace_nested_interval, base_pairs, pair_to_layer)
            continue

        # --- 3. YHX Frame Processing ---
        # YHX has a paired inner hole (k,l) but an undetermined outer span (i,j).
        if tag == "YHX":
            _, outer_start, outer_end, k_idx, l_idx, layer_idx = trace_frame
            place_pair_in_first_non_crossing_layer(base_pairs, pair_to_layer, k_idx, l_idx, layer_idx)
            logger.debug(f"YHX[{outer_start},{outer_end},{k_idx},{l_idx}] layer={layer_idx}")


            backpointer = get_yhx_backpointer(eddy_rivas_fold_state, outer_start, outer_end, k_idx, l_idx)
            if not backpointer:
                print(f"[YHX MISS] ({outer_start},{outer_end}:{k_idx},{l_idx}) layer={layer_idx} → no BP", flush=True)
                continue

            op = backpointer.op

            # 3.1. For adding dangles or unpaired bases, push the corresponding smaller subproblem.
            if op is EddyRivasBacktrackOp.RE_YHX_DANGLE_L:
                trace_stack.append(("VHX", outer_start + 1, outer_end, k_idx, l_idx, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_YHX_DANGLE_R:
                trace_stack.append(("VHX", outer_start, outer_end - 1, k_idx, l_idx, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_YHX_DANGLE_LR:
                trace_stack.append(("VHX", outer_start + 1, outer_end - 1, k_idx, l_idx, layer_idx))
            # SS trims → push YHX with modified coordinates
            elif op is EddyRivasBacktrackOp.RE_YHX_SS_LEFT:
                trace_stack.append(("YHX", outer_start + 1, outer_end, k_idx, l_idx, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_YHX_SS_RIGHT:
                trace_stack.append(("YHX", outer_start, outer_end - 1, k_idx, l_idx, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_YHX_SS_BOTH:
                trace_stack.append(("YHX", outer_start + 1, outer_end - 1, k_idx, l_idx, layer_idx))

            # 3.2. For wrapping a multiloop around a WHX. This forms the (k,l) pair.
            elif op is EddyRivasBacktrackOp.RE_YHX_WRAP_WHX:
                wi, wj = backpointer.outer if backpointer.outer else (outer_start, outer_end)
                wk, wl = backpointer.hole if backpointer.hole else (k_idx - 1, l_idx + 1)
                trace_stack.append(("WHX", wi, wj, wk, wl, 0))
            elif op is EddyRivasBacktrackOp.RE_YHX_WRAP_WHX_L:
                wi, wj = backpointer.outer if backpointer.outer else (outer_start + 1, outer_end)
                wk, wl = backpointer.hole if backpointer.hole else (k_idx - 1, l_idx + 1)
                trace_stack.append(("WHX", wi, wj, wk, wl, 0))
            elif op is EddyRivasBacktrackOp.RE_YHX_WRAP_WHX_R:
                wi, wj = backpointer.outer if backpointer.outer else (outer_start, outer_end - 1)
                wk, wl = backpointer.hole if backpointer.hole else (k_idx - 1, l_idx + 1)
                trace_stack.append(("WHX", wi, wj, wk, wl, 0))
            elif op is EddyRivasBacktrackOp.RE_YHX_WRAP_WHX_LR:
                wi, wj = backpointer.outer if backpointer.outer else (outer_start + 1, outer_end - 1)
                wk, wl = backpointer.hole if backpointer.hole else (k_idx - 1, l_idx + 1)
                trace_stack.append(("WHX", wi, wj, wk, wl, 0))

            # 3.3. Bifurcation.
            elif op is EddyRivasBacktrackOp.RE_YHX_SPLIT_LEFT_YHX_WX:
                split_index = validate_left_split_index(outer_start, outer_end, backpointer.split)
                if split_index is None:
                    print(f"[YHX SPLIT LEFT] non-progress split → merge [{outer_start},{outer_end}]", flush=True)
                    merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)
                    continue

                trace_stack.append(("YHX", outer_start, split_index, k_idx, l_idx, layer_idx))
                if split_index + 1 <= outer_end:
                    merge_nested_region_pairs(seq, nested_state, split_index + 1, outer_end, 0,
                                              trace_nested_interval, base_pairs, pair_to_layer)

            elif op is EddyRivasBacktrackOp.RE_YHX_SPLIT_RIGHT_WX_YHX:
                split_index = validate_right_split_index(outer_start, outer_end, backpointer.split)
                if split_index is None:
                    print(f"[YHX SPLIT RIGHT] non-progress split → merge [{outer_start},{outer_end}]", flush=True)
                    merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)
                    continue

                if outer_start <= split_index:
                    merge_nested_region_pairs(seq, nested_state, outer_start, split_index, 0,
                                              trace_nested_interval, base_pairs, pair_to_layer)

                if split_index + 1 <= outer_end:
                    trace_stack.append(("YHX", split_index + 1, outer_end, k_idx, l_idx, layer_idx))

            # 3.4. For IS2 motif, delegate to WHX
            elif op is EddyRivasBacktrackOp.RE_YHX_IS2_INNER_WHX:
                if backpointer.bridge:
                    wi, wj = backpointer.bridge
                    # Accept if (a) strict subspan of [i..j], or
                    #         (b) equal span but target WHX will make immediate progress.
                    strict_subspan = (outer_start <= wi <= wj <= outer_end) and ((wi, wj) != (outer_start, outer_end))
                    equal_span = (wi, wj) == (outer_start, outer_end)
                    ok_not_hole = ((wi, wj) != (k_idx, l_idx))
                    # If the inner hole pair (k,l) was already placed (e.g., by
                    # a composing WX backpointer), prefer to merge nested content
                    # rather than hand off to WHX which may collapse the hole.
                    existing_pair_layer = pair_to_layer.get((k_idx, l_idx), 0)
                    if existing_pair_layer and ok_not_hole:
                        print("[YHX IS2] inner hole already placed on higher layer; merging nested instead of WHX", flush=True)
                        merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                                  trace_nested_interval, base_pairs, pair_to_layer)
                        continue
                    if (strict_subspan or (
                            equal_span and _target_will_progress_to_whx(eddy_rivas_fold_state, wi, wj, k_idx,
                                                                        l_idx))) and ok_not_hole:
                        print(f"[YHX IS2] handoff → WHX({wi},{wj}:{k_idx},{l_idx})", flush=True)
                        trace_stack.append(("WHX", wi, wj, k_idx, l_idx, layer_idx))
                        continue
                    print("[YHX IS2] bridge rejected (non-progress or equals hole) → merge nested", flush=True)
                    merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)
                else:
                    print("[YHX IS2] missing bridge → merge nested", flush=True)
                    merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)
                continue

            # 3.6. Unknown operation fallback
            else:
                logger.warning(f"Unknown YHX op: {op}, skipping")

            continue

        # --- 4. ZHX Frame Processing ---
        # ZHX has a paired outer span (i,j) but an undetermined inner hole (k,l).
        if tag == "ZHX":
            _, outer_start, outer_end, k_idx, l_idx, layer_idx = trace_frame

            backpointer = get_zhx_backpointer(eddy_rivas_fold_state, outer_start, outer_end, k_idx, l_idx)
            if not backpointer:
                continue
            op = backpointer.op

            # 4.1. For forming the inner pair (k,l), transition to a VHX sub-problem.
            if op is EddyRivasBacktrackOp.RE_ZHX_FROM_VHX:
                trace_stack.append(("VHX", outer_start, outer_end, k_idx, l_idx, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_ZHX_DANGLE_L:
                trace_stack.append(("VHX", outer_start, outer_end, k_idx, l_idx + 1, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_ZHX_DANGLE_R:
                trace_stack.append(("VHX", outer_start, outer_end, k_idx - 1, l_idx, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_ZHX_DANGLE_LR:
                trace_stack.append(("VHX", outer_start, outer_end, k_idx - 1, l_idx + 1, layer_idx))

            # 4.2. For adding unpaired bases, recurse on a smaller ZHX.
            elif op is EddyRivasBacktrackOp.RE_ZHX_SS_LEFT:
                trace_stack.append(("ZHX", outer_start, outer_end, k_idx - 1, l_idx, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_ZHX_SS_RIGHT:
                trace_stack.append(("ZHX", outer_start, outer_end, k_idx, l_idx + 1, layer_idx))

            # 4.3. Bifurcations
            elif op is EddyRivasBacktrackOp.RE_ZHX_SPLIT_LEFT_ZHX_WX:
                split_index = validate_left_split_index(outer_start, k_idx, backpointer.split)  # Split within [i..k]
                if split_index is None:
                    print(f"[ZHX SPLIT LEFT] non-progress split → merge [{k_idx + 1},{outer_end}]",
                          flush=True)
                    # Choose a safe fallback (merge the WX side)
                    if k_idx + 1 <= outer_end:
                        merge_nested_region_pairs(seq, nested_state, k_idx + 1, outer_end, 0,
                                                  trace_nested_interval, base_pairs, pair_to_layer)
                    continue

                trace_stack.append(("ZHX", outer_start, outer_end, split_index, l_idx, layer_idx))
                if split_index + 1 <= k_idx:
                    merge_nested_region_pairs(seq, nested_state, split_index + 1, k_idx, 0,
                                              trace_nested_interval, base_pairs, pair_to_layer)

            elif op is EddyRivasBacktrackOp.RE_ZHX_SPLIT_RIGHT_ZHX_WX:
                split_index = validate_right_split_index(l_idx, outer_end, backpointer.split)  # split within [l..j]
                if split_index is None:
                    print(f"[ZHX SPLIT RIGHT] non-progress split → merge [{outer_start},{l_idx - 1}]",
                          flush=True)
                    if outer_start <= l_idx - 1:
                        merge_nested_region_pairs(seq, nested_state, outer_start, l_idx - 1, 0,
                                                  trace_nested_interval, base_pairs, pair_to_layer)
                    continue

                trace_stack.append(("ZHX", outer_start, outer_end, k_idx, split_index, layer_idx))
                if l_idx <= split_index - 1:
                    merge_nested_region_pairs(seq, nested_state, l_idx, split_index - 1, 0,
                                              trace_nested_interval, base_pairs, pair_to_layer)

            # 4.4. An IS2 motif,
            elif op is EddyRivasBacktrackOp.RE_ZHX_IS2_INNER_VHX:
                if backpointer.bridge:
                    vi, vj = backpointer.bridge
                    strict_subspan = (outer_start <= vi <= vj <= outer_end) and ((vi, vj) != (outer_start, outer_end))
                    equal_span = (vi, vj) == (outer_start, outer_end)
                    ok_geom = ((vi, vj) != (k_idx, l_idx)) and (k_idx + 1 < l_idx)
                    if (strict_subspan or (
                            equal_span and _target_will_progress_to_vhx(eddy_rivas_fold_state, vi, vj, k_idx,
                                                                        l_idx))) and ok_geom:
                        print(f"[ZHX IS2] handoff → VHX({vi},{vj}:{k_idx},{l_idx})", flush=True)
                        trace_stack.append(("VHX", vi, vj, k_idx, l_idx, layer_idx))
                        continue
                    print("[ZHX IS2] bridge rejected → merge nested", flush=True)
                    merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)
                else:
                    print("[ZHX IS2] missing bridge → merge nested", flush=True)
                continue

            # 4.5. Unknown operation fallback
            else:
                logger.warning(f"Unknown ZHX op: {op}, skipping")

            continue

        # --- 5. VHX Frame Processing ---
        # VHX is the most constrained gapped structure: both (i,j) and (k,l) are paired.
        if tag == "VHX":
            _, outer_start, outer_end, k_idx, l_idx, layer_idx = trace_frame

            backpointer = get_vhx_backpointer(eddy_rivas_fold_state, outer_start, outer_end, k_idx, l_idx)
            if not backpointer:
                print(f"[VHX MISS] ({outer_start},{outer_end}:{k_idx},{l_idx}) layer={layer_idx} → no BP", flush=True)
                continue

            print(f"[VHX] ({outer_start},{outer_end}:{k_idx},{l_idx}) layer={layer_idx} op={backpointer.op}", flush=True)
            op = backpointer.op

            # 5.1. Dangles on the inner pair (k,l).
            if op is EddyRivasBacktrackOp.RE_VHX_DANGLE_L:
                trace_stack.append(("VHX", outer_start, outer_end, k_idx + 1, l_idx, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_VHX_DANGLE_R:
                trace_stack.append(("VHX", outer_start, outer_end, k_idx, l_idx - 1, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_VHX_DANGLE_LR:
                trace_stack.append(("VHX", outer_start, outer_end, k_idx + 1, l_idx - 1, layer_idx))

            # 5.2. For adding unpaired bases, transition to a ZHX sub-problem.
            elif op is EddyRivasBacktrackOp.RE_VHX_SS_LEFT:
                trace_stack.append(("ZHX", outer_start, outer_end, k_idx - 1, l_idx, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_VHX_SS_RIGHT:
                trace_stack.append(("ZHX", outer_start, outer_end, k_idx, l_idx + 1, layer_idx))

            # 5.3. Bifurcation.
            elif op is EddyRivasBacktrackOp.RE_VHX_SPLIT_LEFT_ZHX_WX:
                split_index = validate_left_split_index(outer_start, k_idx, backpointer.split)
                if split_index is None:
                    print(f"[VHX SPLIT LEFT] non-progress split → merge [{k_idx + 1},{outer_end}]",
                          flush=True)
                    if k_idx + 1 <= outer_end:
                        merge_nested_region_pairs(seq, nested_state, k_idx + 1, outer_end, 0,
                                                  trace_nested_interval, base_pairs, pair_to_layer)
                    continue
                trace_stack.append(("ZHX", outer_start, outer_end, split_index, l_idx, layer_idx))
                if split_index + 1 <= k_idx:
                    merge_nested_region_pairs(seq, nested_state, split_index + 1, k_idx, 0,
                                              trace_nested_interval, base_pairs, pair_to_layer)

            elif op is EddyRivasBacktrackOp.RE_VHX_SPLIT_RIGHT_ZHX_WX:
                split_index = backpointer.split if backpointer.split is not None else (l_idx + outer_end) // 2
                if split_index is None:
                    print(f"[VHX SPLIT RIGHT] non-progress split → merge [{outer_start},{l_idx - 1}]",
                          flush=True)
                    if outer_start <= l_idx - 1:
                        merge_nested_region_pairs(seq, nested_state, outer_start, l_idx - 1, 0,
                                                  trace_nested_interval, base_pairs, pair_to_layer)
                    continue
                trace_stack.append(("ZHX", outer_start, outer_end, k_idx, split_index, layer_idx))
                merge_nested_region_pairs(seq, nested_state, outer_start, split_index, 0,
                                          trace_nested_interval, base_pairs, pair_to_layer)

            # 5.4. An IS2 motif.
            elif op is EddyRivasBacktrackOp.RE_VHX_IS2_INNER_ZHX:
                if backpointer.bridge:
                    zi, zj = backpointer.bridge
                    strict_subspan = (outer_start <= zi <= zj <= outer_end) and ((zi, zj) != (outer_start, outer_end))
                    equal_span = (zi, zj) == (outer_start, outer_end)
                    ok_not_hole = ((zi, zj) != (k_idx, l_idx))
                    if (strict_subspan or (
                            equal_span and _target_will_progress_to_zhx(eddy_rivas_fold_state, zi, zj, k_idx,
                                                                        l_idx))) and ok_not_hole:
                        print(f"[VHX IS2] handoff → ZHX({zi},{zj}:{k_idx},{l_idx})", flush=True)
                        trace_stack.append(("ZHX", zi, zj, k_idx, l_idx, layer_idx))
                        continue
                    print("[VHX IS2] bridge rejected → merge nested", flush=True)
                    merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)
                else:
                    print("[VHX IS2] missing bridge → merge nested", flush=True)
                continue

            # 5.5. Mulitloop wrap
            elif op is EddyRivasBacktrackOp.RE_VHX_WRAP_WHX:
                (wi, wj) = backpointer.outer if backpointer.outer else (outer_start, outer_end)
                trace_stack.append(("WHX", wi, wj, k_idx, l_idx, 0))

            # 5.6. Where BOTH pairs (i,j) and (k,l) are formed simultaneously.
            elif op is EddyRivasBacktrackOp.RE_VHX_CLOSE_BOTH:
                # Place both helices, assigning them to non-conflicting layers.
                layer_outer = place_pair_in_first_non_crossing_layer(
                    base_pairs, pair_to_layer, outer_start, outer_end, layer_idx
                )  # outer helix
                layer_inner = place_pair_in_first_non_crossing_layer(
                    base_pairs, pair_to_layer, k_idx, l_idx, layer_idx
                )  # inner helix

                # Optional debug to see where they landed
                if layer_outer != layer_idx or layer_inner != layer_idx:
                    print(
                        f"[BUMP] VHX_CLOSE_BOTH: outer({outer_start},{outer_end})→L{layer_outer}, inner({k_idx},{l_idx})→L{layer_inner}",
                        flush=True
                    )

                # The content inside the multiloop is a nested WHX structure.
                if backpointer.outer and backpointer.hole:
                    wi, wj = backpointer.outer
                    wk, wl = backpointer.hole
                    trace_stack.append(("WHX", wi, wj, wk, wl, 0))

            continue

    # --- Finalization ---
    # Sort the collected pairs by their 5' index.
    ordered_pairs = sorted(base_pairs, key=lambda pr: (pr.base_i, pr.base_j))

    # Convert the pairs and their layer assignments into a multilayer dot-bracket string.
    dot_bracket = pairs_to_multilayer_dotbracket(seq_len, ordered_pairs, pair_to_layer)

    # Perform a final sanity check on the layer assignments.
    audit_layer_assignments(pair_to_layer)

    # Log the final results and performance and return final structure.
    elapsed = time.perf_counter() - start_time
    logger.info(f"Traceback completed in {elapsed:.3f}s")
    logger.info(f"Found {len(ordered_pairs)} base pairs")

    # Debug dump for developer: write pair assignment map and ordered pairs to a tmp file
    try:
        with open('/tmp/trace_debug_pairs.txt', 'w') as dbg:
            dbg.write(f'ordered_pairs={ordered_pairs}\n')
            dbg.write(f'pair_to_layer={pair_to_layer}\n')
            dbg.write(f'base_pairs_set={[ (p.base_i,p.base_j) for p in base_pairs ]}\n')
    except Exception:
        pass

    # Also write a concise final trace file for easy inspection by tooling/users.
    try:
        with open('/tmp/final_trace_result.txt', 'w') as out:
            out.write(f'dot_bracket={dot_bracket}\n')
            out.write(f'ordered_pairs={ordered_pairs}\n')
            out.write(f'pair_to_layer={pair_to_layer}\n')
    except Exception:
        pass

    return TraceResult(pairs=ordered_pairs, dot_bracket=dot_bracket)
