from __future__ import annotations
from typing import List, Tuple, Dict, Set, Callable, Any
import time
import logging

from rna_pk_fold.structures import Pair
from rna_pk_fold.folding.common_traceback import pairs_to_multilayer_dotbracket, TraceResult
from rna_pk_fold.folding.eddy_rivas.eddy_rivas_fold_state import EddyRivasFoldState
from rna_pk_fold.folding.eddy_rivas.eddy_rivas_dynamic_programming import EddyRivasBacktrackOp
from rna_pk_fold.utils.dynamic_programming.traceback_ops_utils import (merge_nested_region_pairs,
                                                                       place_pair_in_first_non_crossing_layer,
                                                                       audit_layer_assignments)
from rna_pk_fold.utils.dynamic_programming.back_pointer_utils import get_wx_backpointer, get_whx_backpointer, get_yhx_backpointer, get_zhx_backpointer, get_vhx_backpointer

logger = logging.getLogger(__name__)


def traceback_with_pseudoknots(
    seq: str,
    *,
    nested_state: Any,
    eddy_rivas_fold_state: EddyRivasFoldState,
    trace_nested_interval: Callable[[str, Any, int, int], TraceResult],
) -> TraceResult:
    """
    Reconstructs the optimal RNA secondary structure, including pseudoknots.

    This function implements a stack-based state machine to navigate the
    backpointers generated by the Rivas-Eddy dynamic programming algorithm.
    It starts from the top-level structure `WX(0, N-1)` and recursively
    decomposes it into smaller subproblems (frames) until the entire
    structure is resolved into a set of base pairs.

    Nested substructures are delegated to an external traceback function,
    allowing this implementation to focus solely on resolving the pseudoknotted
    grammar.

    Parameters
    ----------
    seq : str
        The RNA sequence that was folded.
    nested_state : Any
        The state object from the nested-only folding engine (e.g.,
        ZuckerFoldState). This is treated as an opaque object and is passed
        directly to the `trace_nested_interval` function.
    eddy_rivas_fold_state : EddyRivasFoldState
        The state object containing the filled dynamic programming matrices
        and backpointers from the Rivas-Eddy algorithm.
    trace_nested_interval : Callable[[str, Any, int, int], TraceResult]
        A function responsible for tracing a purely nested secondary
        structure within a given interval `[i, j]`.

    Returns
    -------
    TraceResult
        A data object containing the final list of base pairs and the
        corresponding multilayer dot-bracket string representation.
    """
    start_time = time.perf_counter()

    seq_len = eddy_rivas_fold_state.seq_len
    if seq_len == 0:
        return TraceResult(pairs=[], dot_bracket="")

    logger.info(f"Starting traceback for sequence length N={seq_len}")

    initial_backpointer = get_wx_backpointer(eddy_rivas_fold_state, 0, seq_len - 1)
    print(f"[TB START] WX[0,{seq_len - 1}] BP: {initial_backpointer}", flush=True)

    # --- State Initialization ---
    # A "trace frame" is a tuple: (TAG, *coordinates, layer)
    # - TAG is one of {"WX", "WHX", "YHX", "ZHX", "VHX"}
    # - Coordinates depend on TAG:
    #     WX:  (i, j, layer)
    #     WHX: (i, j, k, l, layer)
    #     YHX: (i, j, k, l, layer)
    #     ZHX: (i, j, k, l, layer)
    #     VHX: (i, j, k, l, layer)
    TraceFrame = Tuple

    # Start with the entire sequence as a WX problem on layer 0.
    trace_stack: List[TraceFrame] = [("WX", 0, seq_len - 1, 0)]

    # `base_pairs` will store the final set of (i, j) base pairs.
    base_pairs: Set[Pair] = set()

    # `pair_to_layer` maps each base pair to its assigned dot-bracket layer.
    pair_to_layer: Dict[Tuple[int, int], int] = {}

    # --- Debugging Block ---
    # This block probes the initial backpointer for the full sequence to provide
    # immediate insight into the top-level structure/WX decision (nested vs. pseudoknotted).
    top_backpointer = get_wx_backpointer(eddy_rivas_fold_state, 0, seq_len - 1)
    if top_backpointer:
        print(
            f"[WX WIN] op={top_backpointer.op} split={top_backpointer.split} "
            f"hole={top_backpointer.hole} hole_left={top_backpointer.hole_left} hole_right={top_backpointer.hole_right}",
            flush=True
        )
    else:
        print("[WX WIN] None → nested only", flush=True)

    # If the top-level structure is a composition, probe the subproblem backpointers.
    if top_backpointer and top_backpointer.op in (
        EddyRivasBacktrackOp.RE_PK_COMPOSE_WX_YHX_WHX,
        EddyRivasBacktrackOp.RE_PK_COMPOSE_WX_WHX_YHX,
        EddyRivasBacktrackOp.RE_PK_COMPOSE_WX_YHX,
        EddyRivasBacktrackOp.RE_PK_COMPOSE_WX,
    ):
        # Determine the exact coordinates of the left and right sub-holes.
        split_index = top_backpointer.split
        if top_backpointer.hole_left:
            left_k, left_l = top_backpointer.hole_left
        else:
            left_k, left_l = (top_backpointer.hole[0], split_index) if top_backpointer.hole else (None, None)

        if top_backpointer.hole_right:
            right_k, right_l = top_backpointer.hole_right
        else:
            _, l_idx = top_backpointer.hole if top_backpointer.hole else (None, None)
            right_k, right_l = (split_index + 1, l_idx)

        # Check if backpointers exist for the specific subproblems that will be traced.
        y_bp = get_yhx_backpointer(eddy_rivas_fold_state, 0, split_index, left_k, left_l)
        w_bp = get_whx_backpointer(eddy_rivas_fold_state, split_index + 1, seq_len - 1, right_k, right_l)

        print(f"[PROBE] YHX[0,{split_index}:{left_k},{left_l}] BP?",
              "yes" if y_bp else "no",
              f"op={getattr(y_bp, 'op', None)}", flush=True)
        print(f"[PROBE] WHX[{split_index + 1},{seq_len - 1}:{right_k},{right_l}] BP?",
              "yes" if w_bp else "no",
              f"op={getattr(w_bp, 'op', None)}", flush=True)

    # --- Main Traceback Loop ---
    # Process trace frames from the stack until all sub-problems are resolved.
    while trace_stack:
        # Pop the next subproblem to work on.
        trace_frame = trace_stack.pop()
        print(f"[TB POP] {trace_frame}", flush=True)
        tag = trace_frame[0]

        # --- 1. WX Frame Processing ---
        # WX represents the most general problem for an interval [i, j].
        if tag == "WX":
            _, outer_start, outer_end, layer_idx = trace_frame
            backpointer = get_wx_backpointer(eddy_rivas_fold_state, outer_start, outer_end)

            if outer_start == 0 and outer_end == seq_len - 1:
                print(f"[WX PROCESS] bp={backpointer}", flush=True)
                if backpointer:
                    print(f"  op={backpointer.op}", flush=True)

            # 1.1. If no backpointer, or if the backpointer explicitly selects the 'uncharged' (nested) path...
            if not backpointer or backpointer.op is EddyRivasBacktrackOp.RE_WX_SELECT_UNCHARGED:
                if outer_start == 0 and outer_end == seq_len - 1:
                    print(f"  → Going nested!", flush=True)
                # ...delegate this entire interval to the nested traceback function.
                merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                          trace_nested_interval, base_pairs, pair_to_layer)
                continue

            if outer_start == 0 and outer_end == seq_len - 1:
                print(f"  → Processing PK composition!", flush=True)

            op = backpointer.op
            split_index = backpointer.split
            k_idx, l_idx = (backpointer.hole if backpointer.hole is not None else (None, None))

            # 1.2. Handle WX composition from two WHX subproblems.
            if op is EddyRivasBacktrackOp.RE_PK_COMPOSE_WX:
                if backpointer.hole_left and backpointer.hole_right:
                    left_k, left_l = backpointer.hole_left
                    right_k, right_l = backpointer.hole_right
                else:
                    left_k, left_l = k_idx, split_index
                    right_k, right_l = split_index + 1, l_idx

                # Both subproblems are WHX and are considered part of the base nested layer.
                trace_stack.append(("WHX", outer_start, left_l, left_k, left_l, 0))
                trace_stack.append(("WHX", right_k, outer_end, right_k, right_l, 0))
                continue

            # 1.3. Handle WX composition from two YHX subproblems.
            if op is EddyRivasBacktrackOp.RE_PK_COMPOSE_WX_YHX:
                if backpointer.hole_left and backpointer.hole_right:
                    left_k, left_l = backpointer.hole_left
                    right_k, right_l = backpointer.hole_right
                else:
                    left_k, left_l = k_idx, split_index
                    right_k, right_l = split_index + 1, l_idx

                trace_stack.append(("YHX", outer_start, left_l, left_k, left_l, layer_idx))
                trace_stack.append(("YHX", right_k, outer_end, right_k, right_l, layer_idx))
                continue

            # 1.4. Handle WX composition from two overlapping YHX subproblems.
            if op is EddyRivasBacktrackOp.RE_PK_COMPOSE_WX_YHX_OVERLAP:
                # Both branches share the same (k,l); no BPs are needed—YHX will place (k,l) on entry
                trace_stack.append(("YHX", outer_start, split_index, k_idx, l_idx, layer_idx))
                trace_stack.append(("YHX", split_index + 1, outer_end, k_idx, l_idx, layer_idx))
                continue

            # 1.5. Handle WX composition from a YHX (crossing) and a WHX (nested) subproblem.
            if op is EddyRivasBacktrackOp.RE_PK_COMPOSE_WX_YHX_WHX:
                if backpointer.hole_left and backpointer.hole_right:
                    left_k, left_l = backpointer.hole_left
                    right_k, right_l = backpointer.hole_right
                else:
                    left_k, left_l = k_idx, split_index
                    right_k, right_l = split_index + 1, l_idx

                trace_stack.append(("YHX", outer_start, left_l, left_k, left_l, layer_idx))
                trace_stack.append(("WHX", right_k, outer_end, right_k, right_l, 0))
                continue

            # 1.6. Handle WX composition from a WHX (nested) and a YHX (crossing) subproblem.
            if op is EddyRivasBacktrackOp.RE_PK_COMPOSE_WX_WHX_YHX:
                if backpointer.hole_left and backpointer.hole_right:
                    left_k, left_l = backpointer.hole_left
                    right_k, right_l = backpointer.hole_right
                else:
                    left_k, left_l = k_idx, split_index
                    right_k, right_l = split_index + 1, l_idx

                if outer_start == 0 and outer_end == seq_len - 1:
                    print(f"  [PUSH] WHX({outer_start}, {left_l}, {left_k}, {left_l}, 0)", flush=True)
                    print(f"  [PUSH] YHX({right_k}, {outer_end}, {right_k}, {right_l}, {layer_idx})", flush=True)

                trace_stack.append(("WHX", outer_start, left_l, left_k, left_l, 0))
                trace_stack.append(("YHX", right_k, outer_end, right_k, right_l, layer_idx))
                continue

            # 1.6. Fallback for any other WX operation: treat as a simple nested interval.
            merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                      trace_nested_interval, base_pairs, pair_to_layer)
            continue

        # --- 2. WHX Frame Processing ---
        # WHX is a gapped structure with undetermined pairing at all ends.
        if tag == "WHX":
            _, outer_start, outer_end, k_idx, l_idx, layer_idx = trace_frame

            if k_idx + 1 == l_idx:
                print(f"[WHX COLLAPSE] ({outer_start},{outer_end}:{k_idx},{l_idx}) → nested", flush=True)
                merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                          trace_nested_interval, base_pairs, pair_to_layer)
                continue

            logger.debug(f"\n=== WHX[{outer_start},{outer_end},{k_idx},{l_idx}] layer={layer_idx} ===")
            backpointer = get_whx_backpointer(eddy_rivas_fold_state, outer_start, outer_end, k_idx, l_idx)

            # 2.1. If no backpointer, it implies the hole collapsed. Treat the outer span as nested.
            if not backpointer:
                print(f"[WHX MISS] merging nested [{outer_start},{outer_end}] hole=({k_idx},{l_idx}) layer={layer_idx}",
                      flush=True)
                merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                          trace_nested_interval, base_pairs, pair_to_layer)
                continue

            print(
                f"[WHX] ({outer_start},{outer_end}:{k_idx},{l_idx}) layer={layer_idx} op={backpointer.op}",
                flush=True
            )
            op = backpointer.op

            # 2.2. Add an unpaired base at the 5' end of the hole. Push the smaller subproblem.
            if op is EddyRivasBacktrackOp.RE_WHX_SHRINK_LEFT:
                if (k_idx + 1) + 1 == l_idx:
                    # Shrinking left leads to collapse: WHX(i,j:k+1,l) where (k+1)+1==l
                    print(f"[WHX TRANSITIVE COLLAPSE] ({outer_start},{outer_end}:{k_idx},{l_idx}) shrink→collapse",
                          flush=True)
                    merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)
                    continue
                trace_stack.append(("WHX", outer_start, outer_end, k_idx + 1, l_idx, layer_idx))

            # 2.3. Add an unpaired base at the 3' end of the hole.
            elif op is EddyRivasBacktrackOp.RE_WHX_SHRINK_RIGHT:
                if k_idx + 1 == (l_idx - 1):
                    print(f"[WHX TRANSITIVE COLLAPSE] ({outer_start},{outer_end}:{k_idx},{l_idx}) shrink→collapse",
                          flush=True)
                    merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)
                    continue
                trace_stack.append(("WHX", outer_start, outer_end, k_idx, l_idx - 1, layer_idx))

            # 2.4. Add an unpaired base at the 5' end of the outer span.
            elif op is EddyRivasBacktrackOp.RE_WHX_TRIM_LEFT:
                trace_stack.append(("WHX", outer_start + 1, outer_end, k_idx, l_idx, layer_idx))

            # 2.5. Add an unpaired base at the 3' end of the outer span.
            elif op is EddyRivasBacktrackOp.RE_WHX_TRIM_RIGHT:
                trace_stack.append(("WHX", outer_start, outer_end - 1, k_idx, l_idx, layer_idx))

            # 2.6. Add unpaired bases at both outer ends.
            elif op is EddyRivasBacktrackOp.RE_WHX_SS_BOTH:
                trace_stack.append(("WHX", outer_start + 1, outer_end - 1, k_idx, l_idx, layer_idx))

            # 2.7. The hole has collapsed into a purely nested structure.
            elif op is EddyRivasBacktrackOp.RE_WHX_COLLAPSE:
                if backpointer.outer:
                    oi, oj = backpointer.outer
                    merge_nested_region_pairs(seq, nested_state, oi, oj, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)
                else:
                    merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                              trace_nested_interval, base_pairs, pair_to_layer)

            # 2.8. Bifurcation into a smaller WHX and a nested WX.
            elif op is EddyRivasBacktrackOp.RE_WHX_SPLIT_LEFT_WHX_WX:
                split_index = backpointer.split if backpointer.split is not None else (outer_start + outer_end) // 2
                trace_stack.append(("WHX", outer_start, split_index, k_idx, l_idx, layer_idx))
                merge_nested_region_pairs(seq, nested_state, split_index + 1, outer_end, layer_idx,
                                          trace_nested_interval, base_pairs, pair_to_layer)

            # 2.9. Bifurcation into a nested WX and a smaller WHX.
            elif op is EddyRivasBacktrackOp.RE_WHX_SPLIT_RIGHT_WX_WHX:
                s2 = backpointer.split if backpointer.split is not None else (outer_start + outer_end) // 2
                merge_nested_region_pairs(seq, nested_state, outer_start, s2, layer_idx,
                                          trace_nested_interval, base_pairs, pair_to_layer)
                trace_stack.append(("WHX", s2 + 1, outer_end, k_idx, l_idx, layer_idx))

            # 2.10. Overlapping pseudoknot from two smaller WHX subproblems.
            elif op is EddyRivasBacktrackOp.RE_WHX_OVERLAP_SPLIT:
                split_index = backpointer.split if backpointer.split is not None else (outer_start + outer_end) // 2
                trace_stack.append(("WHX", outer_start, split_index, k_idx, l_idx, layer_idx))
                trace_stack.append(("WHX", split_index + 1, outer_end, k_idx, l_idx, layer_idx))

            else:
                # Fallback for unknown operations.
                logger.warning(f"Unknown WHX op: {op}, falling back to nested")
                merge_nested_region_pairs(seq, nested_state, outer_start, outer_end, layer_idx,
                                          trace_nested_interval, base_pairs, pair_to_layer)

            continue

        # --- 3. YHX Frame Processing ---
        # YHX has a paired inner hole (k,l) but an undetermined outer span (i,j).
        if tag == "YHX":
            _, outer_start, outer_end, k_idx, l_idx, layer_idx = trace_frame
            place_pair_in_first_non_crossing_layer(base_pairs, pair_to_layer, k_idx, l_idx, layer_idx)
            logger.debug(f"YHX[{outer_start},{outer_end},{k_idx},{l_idx}] layer={layer_idx}")

            print(f"[YHX PROCESS] ({outer_start},{outer_end}:{k_idx},{l_idx}) layer={layer_idx}", flush=True)

            backpointer = get_yhx_backpointer(eddy_rivas_fold_state, outer_start, outer_end, k_idx, l_idx)
            if not backpointer:
                print(f"[YHX MISS] ({outer_start},{outer_end}:{k_idx},{l_idx}) layer={layer_idx} → no BP", flush=True)
                continue
            print(f"[YHX] ({outer_start},{outer_end}:{k_idx},{l_idx}) layer={layer_idx} op={backpointer.op}", flush=True)
            op = backpointer.op

            # 3.1. For adding dangles or unpaired bases, push the corresponding smaller subproblem.
            if op is EddyRivasBacktrackOp.RE_YHX_DANGLE_L:
                trace_stack.append(("VHX", outer_start + 1, outer_end, k_idx, l_idx, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_YHX_DANGLE_R:
                trace_stack.append(("VHX", outer_start, outer_end - 1, k_idx, l_idx, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_YHX_DANGLE_LR:
                trace_stack.append(("VHX", outer_start + 1, outer_end - 1, k_idx, l_idx, layer_idx))
            # SS trims → push YHX with modified coordinates
            elif op is EddyRivasBacktrackOp.RE_YHX_SS_LEFT:
                trace_stack.append(("YHX", outer_start + 1, outer_end, k_idx, l_idx, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_YHX_SS_RIGHT:
                trace_stack.append(("YHX", outer_start, outer_end - 1, k_idx, l_idx, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_YHX_SS_BOTH:
                trace_stack.append(("YHX", outer_start + 1, outer_end - 1, k_idx, l_idx, layer_idx))

            # 3.2. For wrapping a multiloop around a WHX. This forms the (k,l) pair.
            elif op is EddyRivasBacktrackOp.RE_YHX_WRAP_WHX:
                wi, wj = backpointer.outer if backpointer.outer else (outer_start, outer_end)
                wk, wl = backpointer.hole if backpointer.hole else (k_idx - 1, l_idx + 1)
                trace_stack.append(("WHX", wi, wj, wk, wl, 0))
            elif op is EddyRivasBacktrackOp.RE_YHX_WRAP_WHX_L:
                wi, wj = backpointer.outer if backpointer.outer else (outer_start + 1, outer_end)
                wk, wl = backpointer.hole if backpointer.hole else (k_idx - 1, l_idx + 1)
                trace_stack.append(("WHX", wi, wj, wk, wl, 0))
            elif op is EddyRivasBacktrackOp.RE_YHX_WRAP_WHX_R:
                wi, wj = backpointer.outer if backpointer.outer else (outer_start, outer_end - 1)
                wk, wl = backpointer.hole if backpointer.hole else (k_idx - 1, l_idx + 1)
                trace_stack.append(("WHX", wi, wj, wk, wl, 0))
            elif op is EddyRivasBacktrackOp.RE_YHX_WRAP_WHX_LR:
                wi, wj = backpointer.outer if backpointer.outer else (outer_start + 1, outer_end - 1)
                wk, wl = backpointer.hole if backpointer.hole else (k_idx - 1, l_idx + 1)
                trace_stack.append(("WHX", wi, wj, wk, wl, 0))

            # 3.3. Bifurcation.
            elif op is EddyRivasBacktrackOp.RE_YHX_SPLIT_LEFT_YHX_WX:
                split_index = backpointer.split if backpointer.split is not None else (outer_start + outer_end) // 2
                trace_stack.append(("YHX", outer_start, split_index, k_idx, l_idx, layer_idx))
                merge_nested_region_pairs(seq, nested_state, split_index + 1, outer_end, 0,
                                          trace_nested_interval, base_pairs, pair_to_layer)
            elif op is EddyRivasBacktrackOp.RE_YHX_SPLIT_RIGHT_WX_YHX:
                s2 = backpointer.split if backpointer.split is not None else (outer_start + outer_end) // 2
                merge_nested_region_pairs(seq, nested_state, outer_start, s2, 0,
                                          trace_nested_interval, base_pairs, pair_to_layer)
                trace_stack.append(("YHX", s2 + 1, outer_end, k_idx, l_idx, layer_idx))

            # 3.4. For IS2 motif, delegate to WHX
            elif op is EddyRivasBacktrackOp.RE_YHX_IS2_INNER_WHX:
                (split_index, s2) = backpointer.bridge if backpointer.bridge else (outer_start, outer_end)
                trace_stack.append(("WHX", split_index, s2, k_idx, l_idx, layer_idx))

            # 3.6. Unknown operation fallback
            else:
                logger.warning(f"Unknown YHX op: {op}, skipping")

            continue

        # --- 4. ZHX Frame Processing ---
        # ZHX has a paired outer span (i,j) but an undetermined inner hole (k,l).
        if tag == "ZHX":
            _, outer_start, outer_end, k_idx, l_idx, layer_idx = trace_frame

            backpointer = get_zhx_backpointer(eddy_rivas_fold_state, outer_start, outer_end, k_idx, l_idx)
            if not backpointer:
                continue
            op = backpointer.op

            # 4.1. For forming the inner pair (k,l), transition to a VHX subproblem.
            if op is EddyRivasBacktrackOp.RE_ZHX_FROM_VHX:
                trace_stack.append(("VHX", outer_start, outer_end, k_idx, l_idx, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_ZHX_DANGLE_L:
                trace_stack.append(("VHX", outer_start, outer_end, k_idx, l_idx + 1, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_ZHX_DANGLE_R:
                trace_stack.append(("VHX", outer_start, outer_end, k_idx - 1, l_idx, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_ZHX_DANGLE_LR:
                trace_stack.append(("VHX", outer_start, outer_end, k_idx - 1, l_idx + 1, layer_idx))

            # 4.2. For adding unpaired bases, recurse on a smaller ZHX.
            elif op is EddyRivasBacktrackOp.RE_ZHX_SS_LEFT:
                trace_stack.append(("ZHX", outer_start, outer_end, k_idx - 1, l_idx, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_ZHX_SS_RIGHT:
                trace_stack.append(("ZHX", outer_start, outer_end, k_idx, l_idx + 1, layer_idx))

            # 4.3. Bifurcations
            elif op is EddyRivasBacktrackOp.RE_ZHX_SPLIT_LEFT_ZHX_WX:
                split_index = backpointer.split if backpointer.split is not None else (outer_start + k_idx) // 2
                trace_stack.append(("ZHX", outer_start, outer_end, split_index, l_idx, layer_idx))
                merge_nested_region_pairs(seq, nested_state, split_index + 1, k_idx, 0,
                                          trace_nested_interval, base_pairs, pair_to_layer)
            elif op is EddyRivasBacktrackOp.RE_ZHX_SPLIT_RIGHT_ZHX_WX:
                s2 = backpointer.split if backpointer.split is not None else (l_idx + outer_end) // 2
                trace_stack.append(("ZHX", outer_start, outer_end, k_idx, s2, layer_idx))
                merge_nested_region_pairs(seq, nested_state, l_idx, s2 - 1, 0,
                                          trace_nested_interval, base_pairs, pair_to_layer)

            # 4.4. An IS2 motif,
            elif op is EddyRivasBacktrackOp.RE_ZHX_IS2_INNER_VHX:
                (split_index, s2) = backpointer.bridge if backpointer.bridge else (k_idx, l_idx)
                trace_stack.append(("VHX", split_index, s2, k_idx, l_idx, layer_idx))

            # 4.5. Unknown operation fallback
            else:
                logger.warning(f"Unknown ZHX op: {op}, skipping")

            continue

        # --- 5. VHX Frame Processing ---
        # VHX is the most constrained gapped structure: both (i,j) and (k,l) are paired.
        if tag == "VHX":
            _, outer_start, outer_end, k_idx, l_idx, layer_idx = trace_frame

            backpointer = get_vhx_backpointer(eddy_rivas_fold_state, outer_start, outer_end, k_idx, l_idx)
            if not backpointer:
                print(f"[VHX MISS] ({outer_start},{outer_end}:{k_idx},{l_idx}) layer={layer_idx} → no BP", flush=True)
                continue
            print(f"[VHX] ({outer_start},{outer_end}:{k_idx},{l_idx}) layer={layer_idx} op={backpointer.op}", flush=True)
            op = backpointer.op

            # 5.1. Dangles on the inner pair (k,l).
            if op is EddyRivasBacktrackOp.RE_VHX_DANGLE_L:
                trace_stack.append(("VHX", outer_start, outer_end, k_idx + 1, l_idx, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_VHX_DANGLE_R:
                trace_stack.append(("VHX", outer_start, outer_end, k_idx, l_idx - 1, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_VHX_DANGLE_LR:
                trace_stack.append(("VHX", outer_start, outer_end, k_idx + 1, l_idx - 1, layer_idx))

            # 5.2. For adding unpaired bases, transition to a ZHX subproblem.
            elif op is EddyRivasBacktrackOp.RE_VHX_SS_LEFT:
                trace_stack.append(("ZHX", outer_start, outer_end, k_idx - 1, l_idx, layer_idx))
            elif op is EddyRivasBacktrackOp.RE_VHX_SS_RIGHT:
                trace_stack.append(("ZHX", outer_start, outer_end, k_idx, l_idx + 1, layer_idx))

            # 5.3. Bifurcation.
            elif op is EddyRivasBacktrackOp.RE_VHX_SPLIT_LEFT_ZHX_WX:
                split_index = backpointer.split if backpointer.split is not None else (outer_start + k_idx) // 2
                trace_stack.append(("ZHX", outer_start, outer_end, split_index, l_idx, layer_idx))
                merge_nested_region_pairs(seq, nested_state, split_index + 1, k_idx, 0, trace_nested_interval, base_pairs, pair_to_layer)
            elif op is EddyRivasBacktrackOp.RE_VHX_SPLIT_RIGHT_ZHX_WX:
                s2 = backpointer.split if backpointer.split is not None else (l_idx + outer_end) // 2
                trace_stack.append(("ZHX", outer_start, outer_end, k_idx, s2, layer_idx))
                merge_nested_region_pairs(seq, nested_state, outer_start, s2, 0, trace_nested_interval, base_pairs, pair_to_layer)

            # 5.4. An IS2 motif.
            elif op is EddyRivasBacktrackOp.RE_VHX_IS2_INNER_ZHX:
                (split_index, s2) = backpointer.bridge if backpointer.bridge else (outer_start, outer_end)
                trace_stack.append(("ZHX", split_index, s2, k_idx, l_idx, layer_idx))

            # 5.5. Mulitloop wrap
            elif op is EddyRivasBacktrackOp.RE_VHX_WRAP_WHX:
                (wi, wj) = backpointer.outer if backpointer.outer else (outer_start, outer_end)
                trace_stack.append(("WHX", wi, wj, k_idx, l_idx, 0))

            # 5.6. Where BOTH pairs (i,j) and (k,l) are formed simultaneously.
            elif op is EddyRivasBacktrackOp.RE_VHX_CLOSE_BOTH:
                # Place both helices, assigning them to non-conflicting layers.
                layer_outer = place_pair_in_first_non_crossing_layer(base_pairs, pair_to_layer, outer_start, outer_end, layer_idx)  # outer helix
                layer_inner = place_pair_in_first_non_crossing_layer(base_pairs, pair_to_layer, k_idx, l_idx, layer_idx)  # inner helix

                # Optional debug to see where they landed
                if layer_outer != layer_idx or layer_inner != layer_idx:
                    print(f"[BUMP] VHX_CLOSE_BOTH: outer({outer_start},{outer_end})→L{layer_outer}, inner({k_idx},{l_idx})→L{layer_inner}",
                          flush=True)

                # The content inside the multiloop is a nested WHX structure.
                if backpointer.outer and backpointer.hole:
                    wi, wj = backpointer.outer
                    wk, wl = backpointer.hole
                    trace_stack.append(("WHX", wi, wj, wk, wl, 0))

            continue

    # --- Finalization ---
    # Sort the collected pairs by their 5' index.
    ordered_pairs = sorted(base_pairs, key=lambda pr: (pr.base_i, pr.base_j))

    # Convert the pairs and their layer assignments into a multilayer dot-bracket string.
    dot_bracket = pairs_to_multilayer_dotbracket(seq_len, ordered_pairs, pair_to_layer)

    # Perform a final sanity check on the layer assignments.
    audit_layer_assignments(pair_to_layer)

    # Log the final results and performance and return final structure.
    elapsed = time.perf_counter() - start_time
    logger.info(f"Traceback completed in {elapsed:.3f}s")
    logger.info(f"Found {len(ordered_pairs)} base pairs")

    return TraceResult(pairs=ordered_pairs, dot_bracket=dot_bracket)
